# Docker Compose for InLegalBERT API Development
# ===============================================

version: '3.8'

services:
  ml-api:
    build: .
    container_name: inlegalbert-api
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=info
    volumes:
      # Mount code for development (hot reload)
      - ./:/app
      # Cache models to avoid re-downloading
      - model-cache:/root/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  model-cache:
    driver: local

